### ISSUE TITLE
Access to insights page

### ISSUE THREAD

**Issue by glassnotes** [Robin-Lai-YY/CPEN400Q-Final-Project#1]
Hi @Robin-Lai-YY  thanks for giving me access to the repository! Could you please enable viewing of all "insights" so I can see the details about the contributors? This requires either a Pro account, or to make the repository public (please consult with your group members before doing this). Alternatively, if one of your group member has a pro account perhaps you can transfer ownership / give them admin access and they can enable it.

**Comment by Robin-Lai-YY** [comment]
Thanks for reaching out! Sorry about this.
All my group members agree to make it public, so it is public now!
